server:
  port: 8089 # 端口

spring:
  application:
    name: market-common # 服务id

eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka
    #fetch-registry: true # 拉取服务
    #register-with-eureka: true # 注册自身服务
    registry-fetch-interval-seconds: 10 # 拉取服务间隔时间

  instance:
    prefer-ip-address: true # 注册时使用ip而不是主机名
    ip-address: 127.0.0.1 # 指定此实例的ip

