server:
  port: 8081

spring:
  application:
    name: market-goods-service

  # 数据库信息
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/market
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sudo8848

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳时间
    lease-expiration-duration-in-seconds: 15 # 过期时间

    prefer-ip-address: true # 注册时使用ip而不是主机名
    ip-address: 127.0.0.1 # 指定此实例的ip

# Mybatis配置
mybatis:
  type-aliases-package: fun.franxx.market.goods.domain # mybatis扫描包名/domain
